name: Docker Base Image CI

on:
  push:
    paths-ignore: 
      - "README.md"
    branches:
    - master
  schedule:
    - cron:  "0 0 * * 0"
  pull_request:
    paths-ignore: 
      - "README.md"
    branches:
    - master


jobs:
  
  build:
    name: Docker Image ${{ matrix.image }} ${{ matrix.tag }} CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: []

    steps:
      - uses: actions/checkout@v1

      - uses: docker/build-push-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            add_git_labels: true
            repository: thost96/appname
            tags: ${{ matrix.tag }}
