name: Docker Image CI

on:
  push:
    paths-ignore: 
      - "README.md"
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  
  build:
    name: Docker CI for wordpress:${{ matrix.tag }} 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [5.6.0-php7.4-apache,5.5.3-php7.4-apache]

    steps:
      - uses: actions/checkout@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      
      - name: Docker Image Build
        uses: docker/build-push-action@v2
        with:
            push: true
            tags: |
              ${{ secrets.DOCKER_USERNAME }}/wordpress:${{ matrix.tag }}      
            build-args: |
              TAG=${{ matrix.tag }}