name: Security Checks

on:
  push:
    paths-ignore:
      - "README.md"
      - ".github/**"
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs: 

  trivy:
     name: Trivy - Scan for Vuls
     runs-on: ubuntu-latest
     strategy:
      fail-fast: false
      matrix:
        tag: [5.6.0-php7.4-apache,5.5.3-php7.4-apache]

     steps:
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Pull Docker Image
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/wordpress:${{ matrix.tag }}

        - name: Trivy Action
          uses: homoluctus/gitrivy@v2
          with:
            image: ${{ secrets.DOCKER_USERNAME }}/wordpress:${{ matrix.tag }}
            token: ${{ secrets.GITHUB_TOKEN }}
            issue: false
  
  snyk:
    name: Snyk - Security Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        tag: [5.6.0-php7.4-apache,5.5.3-php7.4-apache]

    steps:
        - uses: actions/checkout@master

        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/docker@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: ${{ secrets.DOCKER_USERNAME }}/wordpress:${{ matrix.tag }}
            args: --severity-threshold=high