name: Security Checks

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
    - master
  schedule:
    - cron:  "0 0 * * 0"
  pull_request:
    paths-ignore:
      - "README.md"
    branches:
    - master

jobs: 

  trivy:
     name: Trivy - Scan for Vuls
     runs-on: ubuntu-latest
     strategy:
      fail-fast: false
      matrix:
        tag: [5.5.3-php7.4-apache]

     steps:
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        - name: Pull Docker Image
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/wordpress:${{ matrix.tag }}
        - name: Trivy Action
          uses: homoluctus/gitrivy@v2
          with:
            image: ${{ secrets.DOCKER_USERNAME }}/wordpress:${{ matrix.tag }}
            token: ${{ secrets.GITHUB_TOKEN }}
            issue: false
